Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = Split("""
drv_common.c
""")

# add pin drivers.
if GetDepend('RT_USING_PIN'):
    src += ['drv_gpio.c']
    
if GetDepend(['RT_USING_SERIAL']):
    if GetDepend(['RT_USING_SERIAL_V2']):
        src += ['drv_usart_v2.c']
    else:
        src += ['drv_usart.c']

if GetDepend(['BSP_USING_ON_CHIP_FLASH']):
    src += ['drv_flash.c']

if GetDepend('RT_USING_ADC'):
    src += ['drv_adc.c']

if GetDepend('RT_USING_DAC'):
    src += ['drv_dac.c']
if GetDepend('RT_USING_SPI'):
    src += ['drv_spi.c']

if GetDepend('RT_USING_RTC'):
    src += ['drv_rtc.c']

if GetDepend('RT_USING_CAN'):
    src += ['drv_can.c']

if GetDepend('RT_USING_PWM'):
    src += ['drv_pwm.c']

path =  [cwd]
path += [cwd + '/config']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)

Return('group')
